services:
  app:
    init: true
    build:
      context: .
      args:
        - GVITE_VERSION=v2.11.3-nightly-202207201142
        - GVITE_PLATFORM=linux
    ports:
      - ${HOST_WEB_PORT-8989}:80
      - ${HOST_GVITE_HTTP_PORT}:48132
    working_dir: /server
    volumes:
      - ./:/server
      - gvite-executable:/gvite
      - gvite-ledger:/root/.gvite/devdata
      - ./node-config/node_config.json:/gvite/node_config.json
      - ./node-config/genesis.json:/gvite/genesis.json
    command: sh -c "/gvite/gvite -config /gvite/node_config.json >> /gvite/gvite.log 2>&1 & (yarn install && yarn run dev)"
    environment:
      - GVITE_EXECUTABLE=/gvite/gvite
      - VITE_IPC_URL=${VITE_IPC_URL-/root/.gvite/devdata/gvite.ipc}
      - VITE_HTTP_URL=${VITE_HTTP_URL:-app:48132}
      - VITE_SBP_HTTP_URL=${VITE_SBP_HTTP_URL:?VITE_SBP_HTTP_URL env var is required}
      - VITE_WALLET_PRIVATE_KEY=${VITE_WALLET_PRIVATE_KEY:?VITE_WALLET_PRIVATE_KEY env var is required}
      - VITE_WALLET_ADDRESS=${VITE_WALLET_ADDRESS:?VITE_WALLET_ADDRESS env var is required}
      - VITASENSUS_CONTRACT_ADDRESS=${VITASENSUS_CONTRACT_ADDRESS:?VITASENSUS_CONTRACT_ADDRESS env var is required}
      - MONGO_DB_URL=${MONGO_DB_URL-mongodb://root:example@mongo:27017}
      - PORT=${PORT-80}

volumes:
  gvite-executable:
  gvite-ledger: